name: RealEconomy
version: '1.0'
main: de.sirswiperlpp.realeconomy.Main.Main
api-version: '1.21'

commands:
  pay:
    description: The Pay command
    permission: pay.use
  eco:
    description: The Eco command
    permission: eco.use

permissions:
  pay.use:
    default: true
  eco.use:
    default: true
  eco.admin.set:
    default: op
    description: allows permitted to set coins and shards
  eco.admin:
    default: op
    description: generic admin permission